=== LinpgFoundation/VisualNovelScript/examples/vns.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "compiler": {
      "properties": {
        "compiledAt": {
          "type": "integer"
        },
        "reversion": {
          "type": "integer"
        },
        "version": {
          "type": "integer"
        }
      },
      "required": [
        "compiledAt",
        "reversion",
        "version"
      ],
      "type": "object"
    },
    "dialogs": {
      "additionalProperties": {
        "properties": {
          "background_image": {
            "type": "string"
          },
          "background_music": {
            "type": "string"
          },
          "character_images": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "comments": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "contents": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "narrator": {
            "type": "string"
          },
          "next": {
            "properties": {
              "target": {
                "oneOf": [
                  {
                    "type": "string"
                  },
                  {
                    "items": {
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "text": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "text"
                      ],
                      "type": "object"
                    },
                    "type": "array"
                  }
                ]
              },
              "type": {
                "type": "string"
              }
            },
            "required": [
              "type"
            ],
            "type": "object"
          },
          "previous": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "object"
    },
    "id": {
      "type": "string"
    },
    "language": {
      "type": "string"
    }
  },
  "required": [
    "compiler",
    "dialogs",
    "id",
    "language"
  ],
  "type": "object"
}

=== LinpgFoundation/VisualNovelScript/examples/chapter1_dialogs_exp.json
{
    "compiler": {
        "compiledAt": 1707468310,
        "reversion": 0,
        "version": 2
    },
    "dialogs": {
        "dialog_example": {
            "head": {
                "background_image": "bg1.png",
                "background_music": "bgm1.ogg",
                "comments": [
                    "section 1"
                ],
                "contents": [
                    "This is a test message."
                ],
                "next": {
                    "target": "~01",
                    "type": "default"
                }
            },
            "jumping_point1": {
                "background_image": "bg2.png",
                "background_music": "bgm2.ogg",
                "character_images": [
                    "test_character1.png&silent",
                    "test_character2.png&silent"
                ],
                "contents": [
                    "Welcome to jump point 1"
                ],
                "narrator": "Test Character 3",
                "previous": "~04"
            },
            "~01": {
                "background_image": "bg1.png",
                "background_music": "bgm1.ogg",
                "contents": [
                    "I hope it works."
                ],
                "previous": "head"
            },
            "~02": {
                "contents": [
                    "you cannot go back"
                ],
                "next": {
                    "target": "~03",
                    "type": "scene"
                }
            },
            "~03": {
                "background_image": "bg2.png",
                "background_music": "bgm2.ogg",
                "character_images": [
                    "test_character1.png&silent",
                    "test_character2.png&silent"
                ],
                "comments": [
                    "section 2"
                ],
                "contents": [
                    "Hello I am test character 1."
                ],
                "narrator": "Test Character 1",
                "next": {
                    "target": "~04",
                    "type": "default"
                }
            },
            "~04": {
                "background_image": "bg2.png",
                "background_music": "bgm2.ogg",
                "character_images": [
                    "test_character1.png&silent",
                    "test_character2.png&silent"
                ],
                "contents": [
                    "Hello I am test character 2."
                ],
                "narrator": "Test Character 2",
                "next": {
                    "target": [
                        {
                            "id": "jumping_point1",
                            "text": "click here to go to jump point 1"
                        },
                        {
                            "id": "",
                            "text": "click here to go to the end"
                        }
                    ],
                    "type": "options"
                },
                "previous": "~03"
            }
        }
    },
    "id": "1",
    "language": "English"
}
